<?xml version="1.0"?>
<package format="3">
  <name>livelybot_bringup</name>
  <version>0.2.0</version>
  <description>ROS2 bringup and safety nodes for Livelybot.</description>
  <maintainer email="hpx@todo.todo">hpx</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>livelybot_power</depend>
  <depend>livelybot_logger</depend>
  <depend>livelybot_oled</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>

  <exec_depend>livelybot_serial</exec_depend>
  <exec_depend>yesense_imu</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
